### ISSUE TITLE
5.5.8 kernel install error 

### ISSUE THREAD

**Issue by armgong** [archlinux-jerry/pkgbuilds#2]
Today I upgrade 5.5.3 to 5.5.8-1 but it has fatal error , make system can't boot  ,did you still have 5.5.3 or other work version ,I deleted 5.5.3 and now 5.5.8 can't work .

:: Processing package changes...
(1/1) reinstalling linux-phicomm-n1                                                     [###################################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating module dependencies...
(3/4) Updating linux-phicomm-n1 module dependencies...
(4/4) Updating linux-phicomm-n1 initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-phicomm-n1.preset: 'default'
  -> -k 5.5.8-1-ARCH -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-phicomm-n1.img
==> Starting build: 5.5.8-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-phicomm-n1.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux-phicomm-n1.preset: 'fallback'
  -> -k 5.5.8-1-ARCH -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-phicomm-n1-fallback.img -S autodetect
==> Starting build: 5.5.8-1-ARCH
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: ums_eneub6250
==> WARNING: Possibly missing firmware for module: smsmdtv
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
cp: cannot stat '(builtin)': No such file or directory
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-phicomm-n1-fallback.img
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly

**Comment by armgong** [comment]
delete fallback section in  /etc/mkinitcpio.d/linux-phicomm-n1.preset ,and install success

**Comment by isjerryxiao** [comment]
It is caused by an [upstream bug](https://github.com/archlinux/mkinitcpio/pull/17) which has been fixed already and hopefully can be pushed to the repo in a few days.  
Actually fallback initramfs is not used anyway. The current solution is to just delete it or ignore the error.
